In [31]:
import pandas as pd

output = pd.read_excel("output.xlsx")

In [33]:
# переименовываем колонки
output = output.rename(
    columns={
        "Долгота": "lat",
        "Широта": "lon"
    }
)

# сбрасываем индекс
output = output.reset_index(drop=True)

output

                                         Полный адресс        lat        lon
0          Сосенское пос., кв-л 26, з/у 3/3, к. 10.1.5  55.615527  37.482358
1    Рассказовка дер., Переделкино Ближнее мкр., кв...  55.633953  37.334340
2               Льва Кассиля ул., д. 1, к. 1  фаза 17   55.637139  37.306423
3    Лесные Поляны 5-я ул., з/у 20А, к. 1  Рябиновы...  55.961258  37.849508
4                     Александры Монаховой ул., к. 2.3  55.575994  37.471047
..                                                 ...        ...        ...
416          Лаптева ул., з/у 2, к. 3   7 оч., сек. 2   58.741440  61.594267
417                            Рязановское п., к. 11.2  53.938518  49.359994
418                   Александры Монаховой ул., к. 1.1  55.571509  37.477044
419    Марушкинское пос., 33 кв-л, уч. 3, д. 3, к. 3.4  55.599195  37.238568
420                      Николо-Хованское дер., д. 8.1  55.582970  37.468123

[421 rows x 3 columns]

In [32]:
output

                                         Полный адресс    Долгота     Широта
0          Сосенское пос., кв-л 26, з/у 3/3, к. 10.1.5  55.615527  37.482358
1    Рассказовка дер., Переделкино Ближнее мкр., кв...  55.633953  37.334340
2               Льва Кассиля ул., д. 1, к. 1  фаза 17   55.637139  37.306423
3    Лесные Поляны 5-я ул., з/у 20А, к. 1  Рябиновы...  55.961258  37.849508
4                     Александры Монаховой ул., к. 2.3  55.575994  37.471047
..                                                 ...        ...        ...
416          Лаптева ул., з/у 2, к. 3   7 оч., сек. 2   58.741440  61.594267
417                            Рязановское п., к. 11.2  53.938518  49.359994
418                   Александры Монаховой ул., к. 1.1  55.571509  37.477044
419    Марушкинское пос., 33 кв-л, уч. 3, д. 3, к. 3.4  55.599195  37.238568
420                      Николо-Хованское дер., д. 8.1  55.582970  37.468123

[421 rows x 3 columns]

In [27]:
metronew = pd.read_csv("newmetro.csv")
metronew

,Линия,Код станции[1],Название станции\nПрежние названия,Дата\nоткрытия,Пере-\nсадки,"Глубина,\nм[2]",Тип конструкции,Координаты,Вид станции
0,NaN,1,«Бульвар Рокоссовского»\nУлица Подбельского (с...,1 августа 1990,NaN,−8,колонная\nмелкого заложения\nтрёхпролётная,55°48′53″ с. ш. 37°44′03″ в. д.HЯ,NaN
1,NaN,2,«Черкизовская»,1 августа 1990,NaN,−9,односводчатая\nмелкого заложения,55°48′14″ с. ш. 37°44′41″ в. д.HЯ,NaN
2,NaN,3,«Преображенская площадь»,31 декабря 1965,NaN,−8,колонная\nмелкого заложения\nтрёхпролётная,55°47′47″ с. ш. 37°42′54″ в. д.HЯ,NaN
3,NaN,4,«Сокольники»,15 мая 1935,NaN,−9,колонная\nмелкого заложения\nтрёхпролётная,55°47′20″ с. ш. 37°40′49″ в. д.HЯ,NaN
4,NaN,5,«Красносельская»,15 мая 1935,NaN,−8,колонная\nмелкого заложения\nдвухпролётная,55°46′48″ с. ш. 37°40′02″ в. д.HЯ,NaN
...,...,...,...,...,...,...,...,...,...
268,NaN,332,«Генерала Тюленева»,7 сентября 2024,NaN,-20,колонная\nмелкого заложения\nтрёхпролётная,55°37′34″ с. ш. 37°29′10″ в. д.HЯ,NaN
269,NaN,333,«Тютчевская»,7 сентября 2024,NaN,"-12,65",колонная\nмелкого заложения\nтрёхпролётная,55°37′08″ с. ш. 37°28′52″ в. д.HЯ,NaN
270,NaN,335,«Корниловская»,28 декабря 2024,NaN,"-16,18",колонная\nмелкого заложения\nтрёхпролётная,55°35′56″ с. ш. 37°28′45″ в. д.HЯ,NaN
271,NaN,334,«Коммунарка»,28 декабря 2024,NaN,-15,колонная\nмелкого заложения\nдвухпролётная,55°34′29″ с. ш. 37°28′05″ в. д.HЯ,NaN
272,NaN,336,«Новомосковская»,28 декабря 2024,NaN,-8,односводчатая\nмелкого заложения,55°33′38″ с. ш. 37°27′55″ в. д.HЯ,NaN

In [28]:
import re

import re

def dms_to_decimal(dms):
    nums = list(map(float, re.findall(r"\d+", dms)))
    deg, minute, sec = nums[:3]
    return deg + minute / 60 + sec / 3600

metronew["название"] = (
    metronew["Название станции\nПрежние названия"]
    .str.split("\n")
    .str[0]
    .str.replace("«|»", "", regex=True)
)

def extract_lat_lon(s):
    lat_dms = re.search(r"(\d+°\d+′\d+″)\s*с\.?\s*ш\.?", s)
    lon_dms = re.search(r"(\d+°\d+′\d+″)\s*в\.?\s*д\.?", s)

    lat = dms_to_decimal(lat_dms.group(1)) if lat_dms else None
    lon = dms_to_decimal(lon_dms.group(1)) if lon_dms else None

    return pd.Series([lat, lon])

metronew[["lat", "lon"]] = metronew["Координаты"].apply(extract_lat_lon)
metronew

,Линия,Код станции[1],Название станции\nПрежние названия,Дата\nоткрытия,Пере-\nсадки,"Глубина,\nм[2]",Тип конструкции,Координаты,Вид станции,название,lat,lon
0,NaN,1,«Бульвар Рокоссовского»\nУлица Подбельского (с...,1 августа 1990,NaN,−8,колонная\nмелкого заложения\nтрёхпролётная,55°48′53″ с. ш. 37°44′03″ в. д.HЯ,NaN,Бульвар Рокоссовского,55.814722,37.734167
1,NaN,2,«Черкизовская»,1 августа 1990,NaN,−9,односводчатая\nмелкого заложения,55°48′14″ с. ш. 37°44′41″ в. д.HЯ,NaN,Черкизовская,55.803889,37.744722
2,NaN,3,«Преображенская площадь»,31 декабря 1965,NaN,−8,колонная\nмелкого заложения\nтрёхпролётная,55°47′47″ с. ш. 37°42′54″ в. д.HЯ,NaN,Преображенская площадь,55.796389,37.715000
3,NaN,4,«Сокольники»,15 мая 1935,NaN,−9,колонная\nмелкого заложения\nтрёхпролётная,55°47′20″ с. ш. 37°40′49″ в. д.HЯ,NaN,Сокольники,55.788889,37.680278
4,NaN,5,«Красносельская»,15 мая 1935,NaN,−8,колонная\nмелкого заложения\nдвухпролётная,55°46′48″ с. ш. 37°40′02″ в. д.HЯ,NaN,Красносельская,55.780000,37.667222
...,...,...,...,...,...,...,...,...,...,...,...,...
268,NaN,332,«Генерала Тюленева»,7 сентября 2024,NaN,-20,колонная\nмелкого заложения\nтрёхпролётная,55°37′34″ с. ш. 37°29′10″ в. д.HЯ,NaN,Генерала Тюленева,55.626111,37.486111
269,NaN,333,«Тютчевская»,7 сентября 2024,NaN,"-12,65",колонная\nмелкого заложения\nтрёхпролётная,55°37′08″ с. ш. 37°28′52″ в. д.HЯ,NaN,Тютчевская,55.618889,37.481111
270,NaN,335,«Корниловская»,28 декабря 2024,NaN,"-16,18",колонная\nмелкого заложения\nтрёхпролётная,55°35′56″ с. ш. 37°28′45″ в. д.HЯ,NaN,Корниловская,55.598889,37.479167
271,NaN,334,«Коммунарка»,28 декабря 2024,NaN,-15,колонная\nмелкого заложения\nдвухпролётная,55°34′29″ с. ш. 37°28′05″ в. д.HЯ,NaN,Коммунарка,55.574722,37.468056
272,NaN,336,«Новомосковская»,28 декабря 2024,NaN,-8,односводчатая\nмелкого заложения,55°33′38″ с. ш. 37°27′55″ в. д.HЯ,NaN,Новомосковская,55.560556,37.465278

In [30]:
finalmetro = metronew[["название", "lat", "lon"]]
finalmetro

                   название        lat        lon
0     Бульвар Рокоссовского  55.814722  37.734167
1              Черкизовская  55.803889  37.744722
2    Преображенская площадь  55.796389  37.715000
3                Сокольники  55.788889  37.680278
4            Красносельская  55.780000  37.667222
..                      ...        ...        ...
268       Генерала Тюленева  55.626111  37.486111
269              Тютчевская  55.618889  37.481111
270            Корниловская  55.598889  37.479167
271              Коммунарка  55.574722  37.468056
272          Новомосковская  55.560556  37.465278

[273 rows x 3 columns]

In [34]:
import numpy as np
import pandas as pd

def haversine_km(lat1, lon1, lat2, lon2):
    # lat1/lon1: (n,1), lat2/lon2: (1,m)
    R = 6371.0088
    lat1 = np.deg2rad(lat1); lon1 = np.deg2rad(lon1)
    lat2 = np.deg2rad(lat2); lon2 = np.deg2rad(lon2)
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    return 2 * R * np.arcsin(np.sqrt(a))

# на всякий случай приводим к числам
output["lat"] = pd.to_numeric(output["lat"], errors="coerce")
output["lon"] = pd.to_numeric(output["lon"], errors="coerce")
finalmetro["lat"] = pd.to_numeric(finalmetro["lat"], errors="coerce")
finalmetro["lon"] = pd.to_numeric(finalmetro["lon"], errors="coerce")

# матрица расстояний n x m
lat_o = output["lat"].to_numpy()[:, None]
lon_o = output["lon"].to_numpy()[:, None]
lat_m = finalmetro["lat"].to_numpy()[None, :]
lon_m = finalmetro["lon"].to_numpy()[None, :]

dist_km = haversine_km(lat_o, lon_o, lat_m, lon_m)

# индекс ближайшего метро для каждой строки output
idx = np.nanargmin(dist_km, axis=1)

output["ближайшее_метро"] = finalmetro["название"].to_numpy()[idx]
output["расстояние_км"] = dist_km[np.arange(dist_km.shape[0]), idx]
output["расстояние_м"] = (output["расстояние_км"] * 1000).round(0).astype("Int64")

output

/var/folders/ws/lrvlpqj171xc51myg0jksgdr0000gn/T/ipykernel_44768/1872267007.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalmetro["lat"] = pd.to_numeric(finalmetro["lat"], errors="coerce")
/var/folders/ws/lrvlpqj171xc51myg0jksgdr0000gn/T/ipykernel_44768/1872267007.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalmetro["lon"] = pd.to_numeric(finalmetro["lon"], errors="coerce")

,Полный адресс,lat,lon,ближайшее_метро,расстояние_км,расстояние_м
0,"Сосенское пос., кв-л 26, з/у 3/3, к. 10.1.5",55.615527,37.482358,Тютчевская,0.381937,382
1,"Рассказовка дер., Переделкино Ближнее мкр., кв...",55.633953,37.334340,Рассказовка,0.063443,63
2,"Льва Кассиля ул., д. 1, к. 1 фаза 17",55.637139,37.306423,Пыхтино,1.448388,1448
3,"Лесные Поляны 5-я ул., з/у 20А, к. 1 Рябиновы...",55.961258,37.849508,Медведково,14.322433,14322
4,"Александры Монаховой ул., к. 2.3",55.575994,37.471047,Коммунарка,0.235279,235
...,...,...,...,...,...,...
416,"Лаптева ул., з/у 2, к. 3 7 оч., сек. 2",58.741440,61.594267,Некрасовка,1455.864021,1455864
417,"Рязановское п., к. 11.2",53.938518,49.359994,Некрасовка,757.193015,757193
418,"Александры Монаховой ул., к. 1.1",55.571509,37.477044,Коммунарка,0.668513,669
419,"Марушкинское пос., 33 кв-л, уч. 3, д. 3, к. 3.4",55.599195,37.238568,Аэропорт Внуково,3.217480,3217
420,"Николо-Хованское дер., д. 8.1",55.582970,37.468123,Коммунарка,0.917124,917

In [36]:
fo = output[output["расстояние_км"] < 7]
fo.head(50)

,Полный адресс,lat,lon,ближайшее_метро,расстояние_км,расстояние_м
0,"Сосенское пос., кв-л 26, з/у 3/3, к. 10.1.5",55.615527,37.482358,Тютчевская,0.381937,382
1,"Рассказовка дер., Переделкино Ближнее мкр., кв...",55.633953,37.334340,Рассказовка,0.063443,63
2,"Льва Кассиля ул., д. 1, к. 1 фаза 17",55.637139,37.306423,Пыхтино,1.448388,1448
4,"Александры Монаховой ул., к. 2.3",55.575994,37.471047,Коммунарка,0.235279,235
6,"Александры Монаховой ул., к. 6.1.2",55.575436,37.471679,Коммунарка,0.241175,241
8,"вблизи Алхимово дер., д. 8",55.475664,37.507313,Бунинская аллея,6.958350,6958
9,"Дудкино дер., к. 1.3",55.630954,37.454259,Румянцево,0.807538,808
11,"вблизи дер. Середнево, к. 1.1",55.564037,37.289580,Аэропорт Внуково,4.803320,4803
13,"Мосрентген пос., кв-л 24, з/у 1А, к. 2",55.617800,37.472300,Тютчевская,0.566363,566
15,"Льва Кассиля ул., д. 1, к. 3 фаза 17",55.637139,37.306423,Пыхтино,1.448388,1448
16,"Николо-Хованское дер., д. 6.5",55.593597,37.448598,Прокшино,1.243871,1244
20,"Сосенское пос., Столбово дер., к. 3.6.3",55.551128,37.460062,Новомосковская,1.098432,1098
21,"вблизи дер. Середнево, к. 1.3",55.564037,37.289580,Аэропорт Внуково,4.803320,4803
22,"Внуковское пос., ТПУ ""Рассказовка"" тер., з/у 1...",55.632720,37.285688,Пыхтино,1.157447,1157
23,"Сосенское пос., вблизи Столбово дер., уч. 40/2...",55.548935,37.461364,Новомосковская,1.315386,1315
24,"вблизи Зимёнки дер., проект 18/2, кв-л 2, к. 3...",55.573164,37.385448,Прокшино,3.367918,3368
25,"Столбово дер., з/у 41/1Г, д. 3, к. 3.4",55.562047,37.472027,Новомосковская,0.304388,304
26,"Рассказовка дер., кв-л 19, з/у 2, к. 1 фаза 18",55.633953,37.334340,Рассказовка,0.063443,63
27,"Александры Монаховой ул., з/у 87, к. 3.7.2",55.541086,37.490551,Потапово,1.340224,1340
29,"Льва Кассиля ул., д. 1, к. 2 фаза 17",55.637139,37.306423,Пыхтино,1.448388,1448
31,"Дудкино дер., к. 2.2",55.630583,37.453711,Румянцево,0.788106,788
34,"Николо-Хованское дер., д. 4.2",55.595024,37.443160,Прокшино,1.149558,1150
35,"Николо-Хованское дер., д. 5.1.1",55.595730,37.444636,Прокшино,1.264940,1265
37,"Александры Монаховой ул., к. 3.4",55.571509,37.477044,Коммунарка,0.668513,669
38,"Николо-Хованское дер., д. 5.1.2",55.595730,37.444636,Прокшино,1.264940,1265
41,"Мосрентген, Дудкино дер., д. 1",55.632989,37.458950,Румянцево,1.067462,1067
42,"Рассказовка дер., д. 15 4 оч.",55.629211,37.336511,Рассказовка,0.556399,556
43,"Филимонковское пос., Староселье дер., к. 8 Сити",55.554602,37.316938,Аэропорт Внуково,6.131487,6131
44,"Столбово дер., з/у 41/1Г, д. 2, к. 2.5",55.562398,37.472261,Новомосковская,0.341444,341
45,"Столбово дер., з/у 41/1Г, д. 7, к. 7.2",55.561960,37.470860,Новомосковская,0.245427,245
46,"Филимонковское пос., ОАО Марьинская птицефабри...",55.565347,37.319921,Аэропорт Внуково,5.075604,5076
47,"Первый Московский мкр., к. 4 11 оч.",55.603047,37.355985,Филатов Луг,3.258717,3259
50,"Саларьевская ул., з/у 17, к. 83.2",55.613326,37.410726,Саларьево,1.276990,1277
51,"Десна дер., к. 9/1.2",55.528488,37.381432,Новомосковская,6.366928,6367
52,"Газопровод пос., к. Essense сек. 8, этап 2",55.577403,37.476878,Коммунарка,0.629598,630
53,"вблизи Алхимово дер., д. 15",55.476592,37.505660,Бунинская аллея,6.864403,6864
54,"Московский пос., кв-л 70, уч. 78, к. 6 сек. 2",55.602167,37.346611,Рассказовка,3.628720,3629
55,"между Трёхполье ул., з/у 6 и Саларьевская ул.,...",55.613326,37.410726,Саларьево,1.276990,1277
56,"Сосенское пос., Столбово дер., к. 3.8.1",55.551128,37.460062,Новомосковская,1.098432,1098
57,"Сосенское пос., вблизи Столбово дер., уч. 40/1...",55.548528,37.462561,Новомосковская,1.348287,1348
58,"Сосенское пос., Столбово дер., к. 3.5.1",55.551128,37.460062,Новомосковская,1.098432,1098
60,"Харлампиева ул., з/у 32 1 оч., сек. 1-2",55.550845,37.318936,Аэропорт Внуково,6.567668,6568
62,"Московский пос., кв-л 70, уч. 78, к. 1 сек. 2-5",55.602167,37.346611,Рассказовка,3.628720,3629
63,"Поляны ул., з/у 50Д, д. 18.2, к. 18.2.2",55.592256,37.474884,Корниловская,0.785094,785
64,"Московский пос., Картмазово дер., уч. 16/1, к. 5",55.615485,37.389209,Филатов Луг,1.953723,1954
65,"Столбово дер., з/у 41/1Г, д. 5, к. 5.1",55.562266,37.471174,Новомосковская,0.284228,284
66,"Николо-Хованское дер., д. 5.1.4",55.595730,37.444636,Прокшино,1.264940,1265
67,"Александры Монаховой ул., к. 2.1",55.575994,37.471047,Коммунарка,0.235279,235
68,"Сосенское пос., Коммунарка пос., к. 15",55.561134,37.473188,Новомосковская,0.319764,320
69,"Столбово дер., з/у 41/1Г, д. 7, к. 7.3",55.561960,37.470860,Новомосковская,0.245427,245

In [37]:
fo.to_csv("geotometro.csv")